[server]
maxMessageSize = 500

[theme]
base = "dark"
primaryColor = "#00E5FF"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1a1f2e"
textColor = "#ffffff"

[browser]
gatherUsageStats = false